services:
  mysql:
    container_name: cseti-mysql
    volumes:
      - ../mysql/:/usr/citizenseti/mysql
    image: mysql
    ports:
      - "3306:3306"
    env_file: ./files/cseti.env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
  web:
    container_name: cseti-web
    build: web/
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    volumes:
      - ../web/:/usr/citizenseti/web
    command: /usr/citizenseti/web/start.sh
    ports:
      - "443:443"
      - "80:80"
    env_file: ./files/cseti.env
    depends_on:
      mysql:
        condition: service_healthy
